version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-28-alpha  # gcloud is baked into this image
    working_directory: ~/project

jobs:
  build_and_setup:
    executor: android-executor
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Build debug APK and release APK
          command: |
            cd BasicSample
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
            cd ../TwoWaySample
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
            cd ..
      - run:
          name: Store Google Service Account
          command: echo $GCLOUD_SERVICE_KEY | base64 -di > ${HOME}/gcloud-service-key.json
      - run:
          name: Authorize gcloud and set config defaults
          command: |
            sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - persist_to_workspace:
          root: .
          paths:
            - ./*/build
  test1:
    executor: android-executor
    steps:
      - attach_workspace:
          at: project
      - run:
          name: Test BasicSample with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run \
              --app BasicSample/app/build/outputs/apk/debug/app-debug.apk \
              --test BasicSample/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --results-bucket cloud-test-${GOOGLE_PROJECT_ID}-databindingbasic
  test2:
    executor: android-executor
    steps:
      - attach_workspace:
          at: project
      - run:
          name: Test 2-way sample with Firebase Test Lab
          command: >
            sudo gcloud firebase test android run \ 
              --app TwoWaySample/app/build/outputs/apk/debug/app-debug.apk \ 
              --test TwoWaySample/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --results-bucket cloud-test-${GOOGLE_PROJECT_ID}-databindingtwoway
  upload_results:
    executor: android-executor
    steps:
      - attach_workspace:
          at: project
      - run:
          name: Install gsutil dependency and copy test results data
          command: |
            sudo pip install -U crcmod
            sudo gsutil -m cp -r -U `sudo gsutil ls gs://[BUCKET_NAME]/[OBJECT_NAME] | tail -1` ${CIRCLE_ARTIFACTS}/ | true

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_and_setup
      - test1:
          requires: build_and_setup
      - test2:
          requires: build_and_setup
      - upload_results:
          requires:
            - test1
            - test2

