version: 2

setup_ftl: &setup_ftl
  - run:
      name: Authorize gcloud and set config defaults
      command: |
        echo $GCLOUD_SERVICE_KEY | base64 -di > ${HOME}/gcloud-service-key.json
        sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
        sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}

jobs:
  build_and_setup:
    docker:
      - image: circleci/android:api-28-alpha  # gcloud is baked into this image
    working_directory: ~/project
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Build debug APK and release APK
          command: |
            cd BasicSample
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
            cd ../TwoWaySample
            ./gradlew :app:assembleDebug
            ./gradlew :app:assembleDebugAndroidTest
            cd ..
      - persist_to_workspace:
          root: .
          paths:
            - ./*/app/build
  test_basic_sample:
    docker:
      - image: circleci/android:api-28-alpha  # gcloud is baked into this image
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - <<: *setup_ftl
      - run:
          name: Test BasicSample with Firebase Test Lab
          command: |
            sudo gcloud firebase test android run \
              --app BasicSample/app/build/outputs/apk/debug/app-debug.apk \
              --test BasicSample/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --results-bucket cloud-test-${GOOGLE_PROJECT_ID}-databindingbasic \
              --results-dir=build_${CIRCLE_BUILD_NUM}
      - run:
         name: Download results
         command: |
            BUILD_DIR=build_${CIRCLE_BUILD_NUM}
            sudo pip install -U crcmod
            mkdir firebase_test_results
            sudo gsutil -m mv -r -U `sudo gsutil ls gs://cloud-test-${GOOGLE_PROJECT_ID}-databindingbasic/${BUILD_DIR} | tail -1` firebase_test_results/ | true
      - store_artifacts:
          path: firebase_test_results
          
  test_twoway_sample:
    docker:
      - image: circleci/android:api-28-alpha  # gcloud is baked into this image
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - <<: *setup_ftl
      - run:
          name: Test 2-way sample with Firebase Test Lab
          command: |
            sudo gcloud firebase test android run \
              --app TwoWaySample/app/build/outputs/apk/debug/app-debug.apk \
              --test TwoWaySample/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
              --results-bucket cloud-test-${GOOGLE_PROJECT_ID}-databindingtwoway \
              --results-dir=build_${CIRCLE_BUILD_NUM}
      - run:
         name: Download results
         command: |
            BUILD_DIR=build_${CIRCLE_BUILD_NUM}
            sudo pip install -U crcmod
            mkdir firebase_test_results
            sudo gsutil -m mv -r -U `sudo gsutil ls gs://cloud-test-${GOOGLE_PROJECT_ID}-databindingtwoway/${BUILD_DIR} | tail -1` firebase_test_results/ | true
      - store_artifacts:
          path: firebase_test_results


workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_setup
      - test_basic_sample:
          requires:
            - build_and_setup
      - test_twoway_sample:
          requires:
            - build_and_setup
